name: Update BTFHub Archive

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch: {}

jobs:
  build:
    name: Update BTF Archive

    runs-on: ubuntu-latest

    env:
      HOME: "/tmp/root"
      GOPATH: "/tmp/go"
      GOCACHE: "/tmp/go-cache"
      GOROOT: "/usr/local/go"

    steps:
      - name: Setup Swap File
        run: |
          sudo fallocate -l 16G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile

      - name: Install needed ubuntu packages
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo dpkg --purge unattended-upgrades
          sudo apt-get update
          sudo apt-get install -y bsdutils build-essential pkgconf
          sudo apt-get install -y zlib1g-dev libelf-dev
          sudo apt-get install -y software-properties-common
          sudo apt-get install -y devscripts ubuntu-dev-tools

      - name: Update alternatives for LLVM
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo update-alternatives --remove-all cc || true
          # (rest of the LLVM alternatives configuration)

      - name: Authenticate
        run: gh auth login --with-token "${{ secrets.ORG_REPO_TOKEN }}"

      - name: Check out BTFHub
        uses: actions/checkout@v2
        with:
          repository: khulnasoft-lab/btfhub
          path: ./btfhub

      - name: Checkout BTFHub Archive
        uses: actions/checkout@v2
        with:
          repository: khulnasoft-lab/btfhub-archive
          path: ./btfhub-archive

      - name: Install pahole
        run: |
          cd btfhub 
          ./3rdparty/pahole.sh

      - name: Install bpftool
        run: |
          cd btfhub
          ./3rdparty/bpftool.sh

      - name: Bring current BTFHub Archive
        run: |
          cd btfhub 
          make bring

      - name: Compile BTFHub Tool
        run: |
          cd btfhub 
          make

      - name: Fetch and Generate new BTFs (UBUNTU)
        run: |
          cd btfhub
          ./btfhub -workers 6 -d ubuntu

      - name: Fetch and Generate new BTFs (DEBIAN)
        run: |
          cd btfhub
          ./btfhub -workers 6 -d debian -r buster
          ./btfhub -workers 6 -d debian -r bullseye

      - name: Fetch and Generate new BTFs (CENTOS)
        run: |
          cd btfhub
          ./btfhub -workers 6 -d centos

      - name: Fetch and Generate new BTFs (FEDORA)
        run: |
          cd btfhub
          ./btfhub -workers 6 -d fedora

      - name: Fetch and Generate new BTFs (ORACLE)
        run: |
          cd btfhub
          ./btfhub -workers 6 -d ol

      - name: Take new BTFs to BTFHub Archive
        run: |
          cd btfhub
          make take

      - name: Check Status
        run: |
          cd btfhub-archive
          git status

      - name: Commit and Push to BTFHub Archive
        run: |
          cd btfhub-archive
          git config --local user.name "nxpkg"
          git config --local user.email "iconmamundentist@gmail.com"
          git add -A
          git diff-index --quiet HEAD || git commit -m "Update BTFHUB Archive from BTFHUB"
          git push
